import {
    Home,
    Mine,
    Cinema,
    Like,
    Login,
    Search,
    City,
    Show,
    Pe,
    Fun,
    Huj,
    Music,
    Detial
} from "@pages"

export const tabBarRoute = [
    {
        path:"/home",
        component:Home,
        meta:{
            flag:true,
            headFlag:false,
            headerFlag:false
        },
        name:"首页",
        icon:"\ue503"
    },

    {
        path:"/cinema",
        component:Cinema,
        meta:{
            flag:true,
            auth:false
        },
        name:"剧院",
        icon:"\ue618"
    },
    {
        path:"/like",
        component:Like,
        meta:{
            flag:true
        },
        name:"票夹",
        icon:"\ue50b"
    },
    {
        path:"/mine",
        component:Mine,
        meta:{
            flag:true,
            auth:true
        },
        name:"我的",
        icon:"\ue504"
    },
]

export const noTabBarRoute = [
    {
        path:"/login",
        component:Login,
        meta:{
            flag:false,
            headerFlag:false
        },
        name:"登陆",
       
    },
    {
        path:"/city",
        component:City,
        meta:{
            flag:false
        },
        name:"城市",
       
    },
    {
        path:"/search",
        component:Search,
        meta:{
            flag:false
        },
        name:"搜索",
       
    },
    {
        path:"/detial/:id/:name/:timeRange/:venueName/:rank/:lowPrice/:img",
        component:Detial,
        meta:{
            flag:false
        },
        name:"详情页",
    }
]
export const navTabBarRoute = [
    {
        path:"/show",
        component:Show,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"演唱会",
        icon:"\ue690"
    },
    {
        path:"/pe",
        component:Pe,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"体育",
        icon:"\ue6b0"
    },
    {
        path:"/music",
        component:Music,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"音乐会",
       icon:"\ue626"
    },
    {
        path:"/fun",
        component:Fun,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"休闲",
        icon:"\ue6aa"
    },
    {
        path:"/huaju",
        component:Huj,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"话剧",
        icon:"\ue603"
    },
]

export const headTabBar = [
    {
        path:"/show",
        component:Show,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"演唱会",
        icon:"\ue690"
    },
    {
        path:"/pe",
        component:Pe,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"体育赛事",
        icon:"\ue6b0"
    },
    {
        path:"/music",
        component:Music,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"音乐会",
       icon:"\ue626"
    },
    {
        path:"/fun",
        component:Fun,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"休闲娱乐",
        icon:"\ue6aa"
    },
    {
        path:"/huaju",
        component:Huj,
        meta:{
            flag:false,
            headFlag:true,
            headerFlag:true
        },
        name:"戏曲综艺",
        icon:"\ue603"
    },
]

export const routeConfig = tabBarRoute.concat(noTabBarRoute,navTabBarRoute,headTabBar)