import styled from "styled-components"

export const Searche = styled.div`
    width:100%;
    height:100%;
    background:#F2F2F2;
    .search-header{
        width:100%;
        height:.88rem;
        background:#fff;
        border-bottom:1px solid #ccc;
        display:flex;
        position:fixed;
        top:0;
        left:0;
        z-index:10;
        .ui-inner{
            width:75%;
            height:100%;
            input{
                width:98%;
                padding:.18rem;
                margin:.1rem;
                border-radius:.1rem;
                border:none;
                background:#F2F2F2;
                outline-color:#fff;
            }
        }
        .cancel{
            width:15%;
            text-align:center;
            line-height:.88rem;
        }
        .suggest-end{
            width:15%;
            text-align:center;
            line-height:.88rem;
            font-size:.25rem;
            color:#8B8989;
        }
    }
    .search_list{
        width:100%;
        height:max-content;
        padding:.3rem;
        background:#fff;
        margin-top:.5rem;
        a{
            display:block;
            width:100%;
            height:1.66rem;
            border-bottom:1px solid #ccc;
            display:flex;
            margin-top:.1rem;
            .list-img{
                width:15%;
                height:1.6rem;
                img{
                    display:block;
                    width:100%;
                    height:100%;
                }
            }
            .list-info{
                width:80%;
                padding-left:.4rem;
                h3{
                    width:5rem;
                    font-size:.3rem;
                    color:#000;
                    line-height:.6rem;
                    overflow:hidden;
                    text-overflow:ellipsis; 
                    white-space:nowrap;
                }
                .info_{
                    margin-top:.5rem;
                    display:flex;
                    justify-content:space-between;
                    div{
                        span{
                            color:#FFB02E;
                        }
                        i{
                            color:red;
                            font-style:normal;
                            font-size:.28rem;
                        }
                    } 
                }
            }
        }
    }
    .default-search{
        width:100%;
        /* padding-top:.3rem; */
        .row-title{
            width:100%;
            height:.64rem;
            font-size:.25rem;
            padding-left:.2rem;
            line-height:.64rem;
        }
        .hot-searches{
            width:100%;
            height:6.18rem;
            background:#fff;
            padding:.2rem;
            display:flex;
            flex-wrap:wrap;
            .keyword{
                width:max-content;
                height:.72rem;
                border:1px solid #ccc;
                border-radius:.1rem;
                text-align:center;
                line-height:.65rem;
                font-size:.28rem;
                padding: 0 .25rem;
                margin-left:.2rem;
            }
        }
        .search-history{
            width:100%;
            height:6.18rem;
            background:#fff;
            padding:.2rem;
        }
    }
`